export default {
  USER: 'STORAGE_USER',
  WORKSPACE: 'WORK_SPACE',
  DRAFT_REPORT: 'STORAGE_DRAFT_REPORT',
  DRAFT_EXTRA_WORK_ORDER: 'STORAGE_DRAFT_EXTRA_WORK_ORDER',
  DRAFT_TIMESHEET: 'STORAGE_DRAFT_TIMESHEET',
  NOTIFICATION_MESSAGE_ID: 'STORAGE_NOTIFICATION_MESSAGE_ID',
}
