export const NO_NETWORK = 'Network is not available'
export const UNABLE_CONNECT_TO_SERVER = 'Unable to connect to the server'
export const SERVER_ERROR = 'Server error'
export const SUCCESS_MSG = 'Submit successfully'
export const ERROR_MSG = 'Submit failed'
