
import Role from '../constants/role'

export const asBuiltRequirements = [
  {
    'id': 3,
    'created': '2017-10-12T02:42:20Z',
    'name': 'Backfill material',
    'code': 'BF',
    'description': 'Backfill material',
    'data_type': 'string',
    'order': 1,
    'is_mandatory': true,
    'element_category': 1,
  },
  {
    'id': 4,
    'created': '2017-10-12T02:42:45Z',
    'name': 'Surface material',
    'code': 'SF',
    'description': 'Surface material',
    'data_type': 'string',
    'order': 2,
    'is_mandatory': true,
    'element_category': 1,
  },
  {
    'id': 5,
    'created': '2017-10-12T02:40:01Z',
    'name': 'Serial Number id 5',
    'code': 'SN',
    'description': 'Serial Number',
    'data_type': 'string',
    'order': 1,
    'is_mandatory': true,
    'element_category': 2,
  },
  {
    'id': 6,
    'created': '2017-10-12T02:40:01Z',
    'name': 'Serial Number id 6',
    'code': 'SN',
    'description': 'Serial Number',
    'data_type': 'string',
    'order': 1,
    'is_mandatory': true,
    'element_category': 2,
  },
]

export const workItemListNullAsBuiltRequirements = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListNullAsBuiltRequirementsCombined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListWithoutRegionCategory = [
  {
    'id': 29,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': null,
    'region_name': null,
    'network_operator': 191,
    'work_item_category_name': null,
    'work_item_category': null,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListNullAsBuiltRequirementsHasAnnotations = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListNullAsBuiltRequirementsHasAnnotationsCombined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory1 = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory1Combined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [
        {
          'id': 3,
          'name': 'Backfill material',
          'code': 'BF',
          'data_type': 'string',
          'element_category': 1,
        },
        {
          'id': 4,
          'name': 'Surface material',
          'code': 'SF',
          'data_type': 'string',
          'element_category': 1,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory1HasAnnotations = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory1HasAnnotationsCombined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 1,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 4,
          'name': 'Surface material',
          'code': 'SF',
          'data_type': 'string',
          'element_category': 1,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory3 = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 3,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory3Combined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 3,
      'as_built_annotations': [

      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory3HasAnnotations = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 3,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListCategory3HasAnnotationsCombined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': {
      'id': 'd921bc77-37c0-41ce-a47b-340ceddd9cbc',
      'label': 'conduit - 101',
      'the_geom': '{"coordinates": [[[-119.2458485499284, 50.2514567100048], [-119.24583962712256, 50.2515266837492]]], "type": "MultiLineString"}',
      'go_from': 'BB10',
      'go_to': 'AA20',
      'category': 3,
      'as_built_annotations': [
        {
          'id': 21,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Backfill material',
          'code': 'BF',
          'value': '3001',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
        {
          'id': 22,
          'created': '2017-10-17T03:56:28Z',
          'name': 'Surface material By Test',
          'code': 'SF',
          'value': '3002',
          'data_type': 'string',
          'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
          'production_report_line': 133,
        },
      ],
    },
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListNullNetworkElement = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': null,
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const workItemListNullNetworkElementCombined = [
  {
    'id': 28,
    'assign_to_person_full_name': 'Bernie Quora',
    'work_package_name': 'Distribution Network - 3151a',
    'work_item_template_code': '2.56',
    'work_item_template_category_name': 'add desc',
    'quantities': [
      {
        'id': 76,
        'quantity_description_name': 'length (m)',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_factor': '3.28084',
        'quantity_description_unit_system': 'metric',
        'work_item_name': 'OB Plc in Open Trench 103',
        'material_name': null,
        'material_code': null,
        'material_type': null,
        'material_category': null,
        'created': '2017-10-09T19:19:45Z',
        'quantity': 0,
        'estimated_quantity': 200,
        'remaining_quantity': 100,
        'quantity_description': 252,
        'work_item': 28,
        'material': null,
      },
    ],
    'crew_category': 4,
    'crew_category_name': 'Civil',
    'assign_to_crew_name': 'Bill Quora - Cable Installation Crew2',
    'network_operator_material_category': [

    ],
    'assign_to_crew': 2,
    'work_package': 27,
    'work_order_name': 'CIV.DBO - Distribution Network - 3151a',
    'work_order_schedule_end_date': null,
    'requires_photo': false,
    'region': 280,
    'region_name': '3151a',
    'network_operator': 191,
    'work_item_category_name': 'add desc',
    'work_item_category': 2920,
    'network_element': null,
    'created': '2017-10-09T19:19:45Z',
    'name': 'OB Plc in Open Trench 103',
    'description': 'Place and glue in Trench 100mm PVC duct dug by others. Includes all equipment & labour to complete task.',
    'activity_code': '',
    'photo': null,
    'additional_information': '',
    'status': 'assigned',
    'comment': 'well done',
    'date_done': '2017-10-11T02:04:29Z',
    'created_manually': false,
    'work_item_template': 96,
    'work_order': 75,
    'assign_to_person': 16,
  },
]

export const asBuiltRequirementsData = [
  {
    'id': 6,
    'name': 'Surface material By Test',
    'code': 'SF',
    'data_type': 'string',
  },
  {
    'id': 5,
    'name': 'Backfill material By Test',
    'code': 'BF',
    'data_type': 'string',
  },
  {
    'id': 4,
    'name': 'Serial Number By Test',
    'code': 'SN',
    'data_type': 'string',
  },
]

export const asBuiltAnnotationsData = [
  {
    'id': 21,
    'created': '2017-10-17T03:56:28Z',
    'name': 'Backfill material By Test',
    'code': 'BF',
    'value': '3001',
    'data_type': 'string',
    'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
    'production_report_line': 133,
  },
  {
    'id': 22,
    'created': '2017-10-17T03:56:28Z',
    'name': 'Surface material By Test',
    'code': 'SF',
    'value': '3002',
    'data_type': 'string',
    'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
    'production_report_line': 133,
  },
]

export const asBuiltCombineData = [
  {
    'id': 21,
    'created': '2017-10-17T03:56:28Z',
    'name': 'Backfill material By Test',
    'code': 'BF',
    'value': '3001',
    'data_type': 'string',
    'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
    'production_report_line': 133,
  },
  {
    'id': 22,
    'created': '2017-10-17T03:56:28Z',
    'name': 'Surface material By Test',
    'code': 'SF',
    'value': '3002',
    'data_type': 'string',
    'network_element': '0ab108d8-6a54-4270-ba57-3f863d70ec33',
    'production_report_line': 133,
  },
  {
    'id': 4,
    'name': 'Serial Number By Test',
    'code': 'SN',
    'data_type': 'string',
  },
]

export const draftReport = {
  'name': '7274286dddd',
  'reported_date': [2017, 'October', 11],
  'notes': 'aaaa',
  'productReportLines': [
    {
      'activity_code': '412a',
      'comments': '',
      'name': 'string',
      'quantities': [{
        'estimated_quantity': 100,
        'is_primary_quantity': true,
        'material': 1358,
        'material_category': 1024,
        'material_name': 'STUB-432F',
        'material_type': 'STUB-432F',
        'quantity': 100,
        'quantity_description': 493,
        'quantity_description_name': 'cable distance',
        'quantity_description_unit_imperial': 'ft',
        'quantity_description_unit_metric': 'm',
        'quantity_description_unit_system': 'metric',
        'remaining_quantity': 100,
        'work_item_quantity': 1353,
      }],
      'reference_from': 'SV623',
      'reference_to': 'SB31',
      'work_item': 4667,
      'work_item_completed': false,
    },
  ],
  'status': 'Draft',
}

export const workItem = {
  'id': 4313,
  'activity_code': '412A',
  'name': 'Setup splice case',
  'work_item_completed': true,
  'completed_date': '2017-07-20T03:33:35Z',
  'comments': 'This is comment',
  'assign_to_person_full_name': 'Bernie',
  'work_order_name': 'FTTX',
  'quantities': [
    {
      'id': 4851,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 2.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 1.0,
      'quantity_description': 253,
      'material_name': 'CGH-4 cable ground kit sealed AFL closures with something',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
      'is_primary_quantity': true,
    },
    {
      'id': 4852,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 2.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 1.0,
      'quantity_description': 253,
      'material_name': 'AAA',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
    },
    {
      'id': 4853,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 2.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 1.0,
      'quantity_description': 253,
      'material_name': 'BBB',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
    },
  ],
  'network_element': {
    'go_from': 'SV623',
    'go_to': 'SB31',
    'id': 'e2cee669-782e-4b52-8176-94cc5d0bf82d',
    'label': 'cabel-1',
    'the_geom': '{"coordinates": [[[-91.90216779871662, 39.148406432505595], [-91.90232821281158, 39.14827013151372]]], "type": "MultiLineString"}',
    'as_built_annotations': [
      {
        'id': 1,
        'created': '2017-10-12T02:40:01Z',
        'name': 'Serial Number',
        'code': 'SN',
        'description': 'Serial Number',
        'data_type': 'string',
        'order': 1,
        'is_mandatory': true,
        'element_category': 3,
      },
      {
        'id': 2,
        'created': '2017-10-12T02:41:17Z',
        'name': 'Depth of cover',
        'code': 'Depth',
        'description': 'Depth at which conduit is buried',
        'data_type': 'string',
        'order': 2,
        'is_mandatory': true,
        'element_category': 3,
      },
      {
        'id': 3,
        'created': '2017-10-12T02:42:20Z',
        'name': 'Backfill material',
        'code': 'BF',
        'description': 'Backfill material',
        'data_type': 'string',
        'order': 1,
        'is_mandatory': true,
        'element_category': 1,
      },
      {
        'id': 4,
        'created': '2017-10-12T02:42:45Z',
        'name': 'Surface material',
        'code': 'SF',
        'description': 'Surface material',
        'data_type': 'string',
        'order': 2,
        'is_mandatory': true,
        'element_category': 1,
      },
    ],
  },
}

const addedProductReportLines = {
  'activity_code': '412a',
  'comments': '',
  'name': 'string',
  'reference_from': 'SV623',
  'reference_to': 'SB31',
  'work_item': 4313,
  'work_item_completed': false,
}
const productReportLines = [
  ...draftReport.productReportLines,
  addedProductReportLines,
]
export const draftExsitWorkItem = {
  ...draftReport,
  productReportLines,
}

export const reportLineFromWorkItem = {
  'work_item': 4313,
  'activity_code': '412A',
  'work_item_descriptor': 'Setup splice case',
  'reference_from': 'SV623',
  'reference_to': 'SB31',
  'work_item_completed': false,
  'comments': '',
  'quantities': [
    {
      'work_item_quantity': 4851,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 1.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 0,
      'quantity_description': 253,
      'material_name': 'CGH-4 cable ground kit sealed AFL closures with something',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
      'is_primary_quantity': true,
    },
    {
      'work_item_quantity': 4852,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 1.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 0,
      'quantity_description': 253,
      'material_name': 'AAA',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
    },
    {
      'work_item_quantity': 4853,
      'quantity_description_name': 'count (each)',
      'quantity_description_unit_imperial': 'each',
      'quantity_description_unit_metric': 'each',
      'quantity_description_unit_factor': '1.0',
      'quantity_description_unit_system': 'metric',
      'quantity': 1.0,
      'estimated_quantity': 1.0,
      'remaining_quantity': 0,
      'quantity_description': 253,
      'material_name': 'BBB',
      'material_code': 'CGH-4',
      'material_type': 'Terminal',
      'material': 3268,
    },
  ],
  'network_element': {
    'go_from': 'SV623',
    'go_to': 'SB31',
    'id': 'e2cee669-782e-4b52-8176-94cc5d0bf82d',
    'label': 'cabel-1',
    'the_geom': '{"coordinates": [[[-91.90216779871662, 39.148406432505595], [-91.90232821281158, 39.14827013151372]]], "type": "MultiLineString"}',
    'as_built_annotations': [
      {
        'id': 1,
        'created': '2017-10-12T02:40:01Z',
        'name': 'Serial Number',
        'code': 'SN',
        'description': 'Serial Number',
        'data_type': 'string',
        'order': 1,
        'is_mandatory': true,
        'element_category': 3,
      },
      {
        'id': 2,
        'created': '2017-10-12T02:41:17Z',
        'name': 'Depth of cover',
        'code': 'Depth',
        'description': 'Depth at which conduit is buried',
        'data_type': 'string',
        'order': 2,
        'is_mandatory': true,
        'element_category': 3,
      },
      {
        'id': 3,
        'created': '2017-10-12T02:42:20Z',
        'name': 'Backfill material',
        'code': 'BF',
        'description': 'Backfill material',
        'data_type': 'string',
        'order': 1,
        'is_mandatory': true,
        'element_category': 1,
      },
      {
        'id': 4,
        'created': '2017-10-12T02:42:45Z',
        'name': 'Surface material',
        'code': 'SF',
        'description': 'Surface material',
        'data_type': 'string',
        'order': 2,
        'is_mandatory': true,
        'element_category': 1,
      },
    ],
  },
  'pictures': [],
  'is_active': true,
}

export const leadWorker = {
  'id': 11,
  'first_name': 'Bernie',
  'last_name': 'fresnel ',
  'role': Role.LEAD_WORKER,
}

export const constructionManager = {
  'id': 12,
  'first_name': 'Bill',
  'last_name': 'fresnel ',
  'role': Role.CONSTRUCTION_MANAGER,
}

export default asBuiltRequirements
