# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.56.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # Get version from package.json
    file = File.read('../../package.json')
    buildConfig = JSON.parse(file)

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(
      build_number: ENV['CIRCLE_BUILD_NUM'],
      xcodeproj: "VitruviMobile.xcodeproj"
    )

    increment_version_number(
      version_number: buildConfig["version"],      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "VitruviMobile.xcodeproj"  # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
    )

    # Commit the version bump
    commit_version_bump(xcodeproj: "VitruviMobile.xcodeproj", force: true)

    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "VitruviMobile", export_method:"app-store") # Build your app - more options available
    changelog = changelog_from_git_commits(
      commits_count: 2,
      merge_commit_filtering: 'exclude_merges'
    )
    pilot(
      skip_waiting_for_build_processing: true,
      beta_app_description: changelog
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "VitruviMobile") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
