# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # get version from package.json
    file = File.read('../../package.json')
    buildConfig = JSON.parse(file)

    gradle(
      task: "assembleRelease",
      properties: {
        versionCode: ENV['CIRCLE_BUILD_NUM'],
        versionName: buildConfig["version"]
      }
    )

    # Save android apk in CircleCI artifacts, DO NOT RUN THE SENTENCE IT IN LOCAL
    Actions.sh "cp -r ../app/build/outputs #{ENV['CIRCLE_ARTIFACTS']}"

    changelog_from_git_commits(
      commits_count: 2,
      merge_commit_filtering: 'exclude_merges'
    )
    crashlytics(api_token: "3ea7cd54f381be4bc99520632f746d2c9589b1fd",
                build_secret: "ef9e7109b3f8e23d67e3bc5cdd7fc6975e708874a6aa1924e20786722a4c8999")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
